# Generated by Django 5.1.3 on 2024-11-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0002_alter_opportunity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'permissions': [('can_create_opportunity', 'Can create opportunity'), ('can_edit_opportunity', 'Can edit opportunity'), ('can_delete_opportunity', 'Can delete opportunity'), ('can_view_opportunity', 'Can view opportunity')]},
        ),
    ]
