# Generated by Django 5.1.3 on 2024-11-24 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0007_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_opportunities', to=settings.AUTH_USER_MODEL),
        ),
    ]
