# Generated by Django 5.1.3 on 2024-11-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('laboratorio', 'Laboratório'), ('grupo_extensao', 'Grupo de Extensão')], default='aluno', max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
