# Generated by Django 5.1.3 on 2024-11-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0010_profile_user_type_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
